version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: almatyustazy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Olzhastop1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  backend:
    image: ozhek/almatyustazy:latest
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - "8081:8080"
    networks:
      - postgres

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /api.yaml
    ports:
      - "8082:8080"
    volumes:
       - /home/ubuntu/almaty-ustazy/diploma-api/src/main/resources/diploma-api.yml:/api.yaml


networks:
  postgres:
    driver: bridge

volumes:
  postgres: