version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: almatyustazy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Olzhastop1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  backend:
    image: ozhek/almatyustazy:latest
    volumes:
      - /home/ubuntu/almaty_ustazy_backend:/home/app/almaty_ustazy_backend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/home/app/almaty_ustazy_backend/storage_credientials.json
      - DB_URL
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
