version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
    volumes:
      - postgres:/data/postgres
    networks:
      - internal
    restart: unless-stopped

  backend:
    image: ozhek/almatyustazy:v1-prod
    environment:
      - DB_URL=postgres
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    networks:
      - internal
    ports:
      - "8080"
    depends_on:
      - postgres
      - backend-main

  backend-main:
    image: ozhek/almatyustazy:v1-ddl
    environment:
      - DB_URL=postgres
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    networks:
      - internal
    ports:
      - "8080"
    depends_on:
      - postgres

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  internal:
    driver: bridge

volumes:
  postgres: