version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: almatyustazy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Olzhastop1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  backend:
    image: ozhek/almatyustazy:latest
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - "8082:8080"
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
