version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: almatyustazy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Olzhastop1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  backend:
    image: ozhek/almatyustazy:latest
    environment:
      - DB_URL
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    ports:
      - "8080"
    networks:
      - postgres
    depends_on:
      - postgres
  backend-main:
    image: ozhek/almatyustazy:v1-ddl
    environment:
      - DB_URL
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    ports:
      - "8080"
    networks:
      - postgres
    depends_on:
      - postgres

  nginx:
    image: nginx
    container_name: 'nginx-container'
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
