spring:
  application:
    name: diploma-work

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/diploma
    username: test
    password: postgres
    driverClassName: org.postgresql.Driver
